name: "Gathering Wiki Links"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 1 * *"

jobs:
  # Download wiki links
  gathering_links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python -m src.crawler.run
      - run: ls output/
