name: "Gathering Wiki Links"
run-name: Gathering links on "${{ github.ref }}"
on:
  push:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  # Download wiki links
  gathering_links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: pip install
        run: pip install -r requirements.txt
      - run: python -m src.gathering.run
      - name: git config user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: git commit & push
        run: |
          if [[ `git status --porcelain` ]]; then
            git add output/*.csv -f
            git commit -m "ci(crawler-workflow): update base links"
            git push
          else
            echo "No changes were detected."
          fi
        shell: bash
