name: "Gathering Wiki Links"
run-name: Gathering links on "${{ github.ref }}"
on:
  workflow_dispatch:
permissions:
  contents: write

jobs:
  # Download wiki links
  gathering_links:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: uv run -m src.gathering.run
      - name: git config user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: git commit & push
        run: |
          if [[ `git status --porcelain` ]]; then
            git add output/*.csv -f
            git commit -m "ci(crawler-workflow): update base links"
            git push
          else
            echo "No changes were detected."
          fi
        shell: bash
